// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cudydqedykzsvokmrrlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1ZHlkcWVkeWt6c3Zva21ycmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NTgxMjMsImV4cCI6MjA1MjEzNDEyM30.BoQTOJBgGqf-H2F9ZkxEJuOh5lZxB62ialQ3CKu0w3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);